/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistema;

/**
 *
 * @author Vitor
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.Window;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;

public class Login extends javax.swing.JPanel {

    private final DashBoardLogin main;
    public Login(DashBoardLogin main) {
        initComponents();
        carregarDadosSalvos();
            this.main = main;
        }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    btnEntrarActionPerformed(evt); 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAreaLogin = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        cbMostrarSenha = new javax.swing.JCheckBox();
        btnEntrar = new javax.swing.JButton();
        btnNaoTem = new javax.swing.JButton();
        cbLembrarMeusDados = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(30, 30, 30));

        lblAreaLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblAreaLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblAreaLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAreaLogin.setText("Area de Login");

        lblEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(64, 50));

        lblSenha.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");

        txtSenha.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtSenha.setPreferredSize(new java.awt.Dimension(64, 50));

        cbMostrarSenha.setBackground(new java.awt.Color(30, 30, 30));
        cbMostrarSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbMostrarSenha.setForeground(new java.awt.Color(255, 255, 255));
        cbMostrarSenha.setText("Mostrar Senha");
        cbMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarSenhaActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(204, 102, 0));
        btnEntrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorderPainted(false);
        btnEntrar.setPreferredSize(new java.awt.Dimension(0, 50));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnNaoTem.setBackground(new java.awt.Color(41, 41, 41));
        btnNaoTem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnNaoTem.setForeground(new java.awt.Color(255, 255, 255));
        btnNaoTem.setText("Não tem uma conta? Cadastre-se");
        btnNaoTem.setBorderPainted(false);
        btnNaoTem.setPreferredSize(new java.awt.Dimension(0, 50));
        btnNaoTem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaoTemActionPerformed(evt);
            }
        });

        cbLembrarMeusDados.setBackground(new java.awt.Color(30, 30, 30));
        cbLembrarMeusDados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbLembrarMeusDados.setForeground(new java.awt.Color(255, 255, 255));
        cbLembrarMeusDados.setText("Lembrar meus dados");
        cbLembrarMeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLembrarMeusDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAreaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNaoTem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbLembrarMeusDados, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(cbMostrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(lblAreaLogin)
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLembrarMeusDados)
                    .addComponent(cbMostrarSenha))
                .addGap(33, 33, 33)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(btnNaoTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNaoTemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoTemActionPerformed
        // TODO add your handling code here:
        main.setRegister();
    }//GEN-LAST:event_btnNaoTemActionPerformed

    private void cbMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarSenhaActionPerformed
        if (cbMostrarSenha.isSelected()) {
            txtSenha.setEchoChar((char) 0); 
        } else {
            txtSenha.setEchoChar('*'); 
        }
    }//GEN-LAST:event_cbMostrarSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
         btnEntrar.setEnabled(false);
         btnEntrar.setText("Entrando...");

         try {
            Connection conn = Mysql.conectar();
            String sql = "SELECT * FROM usuarios WHERE email = ? AND senha = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, txtEmail.getText());
            stmt.setString(2, new String(txtSenha.getPassword()));
            ResultSet rs = stmt.executeQuery();

            if (cbLembrarMeusDados.isSelected()) {
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("dados_login.txt"))) {
                    writer.write(txtEmail.getText() + "\n");
                    writer.write(new String(txtSenha.getPassword()));
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                File file = new File("dados_login.txt");
                if (file.exists()) {
                    file.delete();
                }
            }

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Login bem-sucedido!");
                new MenuPrincipal().setVisible(true);

                Window window = SwingUtilities.getWindowAncestor(this);
                if (window != null) {
                    window.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Email ou senha incorretos.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao acessar o banco de dados.");
        } finally {
            btnEntrar.setEnabled(true);
            btnEntrar.setText("Entrar");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void cbLembrarMeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLembrarMeusDadosActionPerformed
        if (cbLembrarMeusDados.isSelected()) {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("dados_login.txt"))) {
                writer.write(txtEmail.getText() + "\n");
                writer.write(new String(txtSenha.getPassword()));  // Salva a senha oculta
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            File file = new File("dados_login.txt");
            if (file.exists()) {
                file.delete(); 
            }
        }    
    }//GEN-LAST:event_cbLembrarMeusDadosActionPerformed

    private void carregarDadosSalvos() {
    File file = new File("dados_login.txt");
    if (file.exists()) {
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String email = reader.readLine();
            String senha = reader.readLine();

            if (email != null) {
                txtEmail.setText(email);
            }

            if (senha != null) {
                txtSenha.setText(senha);
            }

            cbLembrarMeusDados.setSelected(true);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnNaoTem;
    private javax.swing.JCheckBox cbLembrarMeusDados;
    private javax.swing.JCheckBox cbMostrarSenha;
    private javax.swing.JLabel lblAreaLogin;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
