/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema;
import com.mycompany.sistema.view.TelaCadastroProdutoView;
import com.mycompany.sistema.view.VerCadastrosView;
import com.mycompany.sistema.DashBoardLogin;
import com.mycompany.sistema.view.CreditosView;

/**
 *
 * @author Vitor
 */
import javax.swing.JFrame;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
    initComponents();
    setResizable(true);
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null); 

    this.setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSairdoSistema = new javax.swing.JButton();
        btnCadastroDeProduto = new javax.swing.JButton();
        btnVerProdutosCadastrados = new javax.swing.JButton();
        btnCreditosDoSistema = new javax.swing.JButton();
        btnVoltarTelaLogin = new javax.swing.JButton();
        jpnEsquerdo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpnDireito = new javax.swing.JPanel();
        jpnBaixo = new javax.swing.JPanel();
        lblSistema = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpnFundo = new javax.swing.JPanel();
        lblImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSairdoSistema.setText("Sair do Sistema");
        btnSairdoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairdoSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairdoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 170, 30));

        btnCadastroDeProduto.setText("Cadastrar Produto");
        btnCadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroDeProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroDeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 170, 30));

        btnVerProdutosCadastrados.setText("Ver Cadastrados");
        btnVerProdutosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProdutosCadastradosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerProdutosCadastrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 170, 30));

        btnCreditosDoSistema.setText("Créditos");
        btnCreditosDoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosDoSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditosDoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 170, 30));

        btnVoltarTelaLogin.setText("← Voltar para Tela de Login");
        btnVoltarTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTelaLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 190, -1));

        jpnEsquerdo.add(jPanel2);

        getContentPane().add(jpnEsquerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 10, 230));
        getContentPane().add(jpnDireito, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 10, 230));
        getContentPane().add(jpnBaixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 310, 10));

        lblSistema.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        lblSistema.setForeground(new java.awt.Color(102, 102, 102));
        lblSistema.setText(" Sistema CadFlex ");
        lblSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        getContentPane().add(lblSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 310, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 310, 60));

        jpnFundo.setBackground(new java.awt.Color(51, 51, 255));
        jpnFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 9));
        getContentPane().add(jpnFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 290, 220));

        lblImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistema/imagens/fundoMenu.png"))); // NOI18N
        lblImagemFundo.setText("jLabel1");
        getContentPane().add(lblImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2020, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairdoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairdoSistemaActionPerformed
        try {
            InputStream input = getClass().getResourceAsStream("/com/mycompany/sistema/files/OBRIGADO_POR_USAR.txt");
            if (input == null) {
                System.out.println("Arquivo de agradecimento não encontrado.");
                return;
            }

            File tempFile = File.createTempFile("OBRIGADO_POR_USAR", ".txt");    
            tempFile.deleteOnExit(); // Remove ao encerrar sistema

            try (OutputStream output = new FileOutputStream(tempFile)) {
                byte[] buffer = new byte[1024];
                int bytesRead;
                while ((bytesRead = input.read(buffer)) != -1) {
                    output.write(buffer, 0, bytesRead);
                }
            }

            Process processo = Runtime.getRuntime().exec("notepad " + tempFile.getAbsolutePath());
            processo.waitFor(); 

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            System.exit(0); 
        }
    }//GEN-LAST:event_btnSairdoSistemaActionPerformed

    private void btnCadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroDeProdutoActionPerformed
       TelaCadastroProdutoView cadastro = new TelaCadastroProdutoView();
       cadastro.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_btnCadastroDeProdutoActionPerformed

    private void btnVerProdutosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProdutosCadastradosActionPerformed
        VerCadastrosView cadastro = new VerCadastrosView();
        cadastro.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVerProdutosCadastradosActionPerformed

    private void btnVoltarTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaLoginActionPerformed
        new DashBoardLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarTelaLoginActionPerformed

    private void btnCreditosDoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosDoSistemaActionPerformed
        CreditosView creditos = new CreditosView();
        creditos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreditosDoSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroDeProduto;
    private javax.swing.JButton btnCreditosDoSistema;
    private javax.swing.JButton btnSairdoSistema;
    private javax.swing.JButton btnVerProdutosCadastrados;
    private javax.swing.JButton btnVoltarTelaLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpnBaixo;
    private javax.swing.JPanel jpnDireito;
    private javax.swing.JPanel jpnEsquerdo;
    private javax.swing.JPanel jpnFundo;
    private javax.swing.JLabel lblImagemFundo;
    private javax.swing.JLabel lblSistema;
    // End of variables declaration//GEN-END:variables
}
