/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.view;
import com.mycompany.sistema.MenuPrincipal;

/**
 *
 * @author Vitor
 */
import javax.swing.JFrame;

public class TelaCadastroProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProdutoView
     */
    public TelaCadastroProdutoView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastroDeProduto = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltarAoMenuPrincipal = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        jpPaineldeFundo = new javax.swing.JPanel();
        jpFundoTexto = new javax.swing.JPanel();
        lblfundoSiCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastroDeProduto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblCadastroDeProduto.setForeground(new java.awt.Color(102, 102, 102));
        lblCadastroDeProduto.setText("CADASTRO DE PRODUTO");
        lblCadastroDeProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(lblCadastroDeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, 60));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 340, 120, 30));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 120, 30));

        btnVoltarAoMenuPrincipal.setText("← Voltar ao Menu Principal");
        btnVoltarAoMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarAoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 760, 200, -1));

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 120, 30));

        jpPaineldeFundo.setBackground(new java.awt.Color(51, 153, 255));
        jpPaineldeFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        jpPaineldeFundo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jpPaineldeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 300, 160));

        jpFundoTexto.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jpFundoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 300, 90));

        lblfundoSiCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistema/imagens/fundoSiCadastro.png"))); // NOI18N
        lblfundoSiCadastro.setText("jLabel1");
        getContentPane().add(lblfundoSiCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1830, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarAoMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuPrincipalActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVoltarAoMenuPrincipalActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
          IncluirView incluirView = new IncluirView();
          incluirView.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
          AlterarView AlterarView = new AlterarView();
          AlterarView.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
          ExcluirView ExcluirView = new ExcluirView();
          ExcluirView.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnVoltarAoMenuPrincipal;
    private javax.swing.JPanel jpFundoTexto;
    private javax.swing.JPanel jpPaineldeFundo;
    private javax.swing.JLabel lblCadastroDeProduto;
    private javax.swing.JLabel lblfundoSiCadastro;
    // End of variables declaration//GEN-END:variables
}
