/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.view;

import com.mycompany.sistema.MenuPrincipal;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class CreditosView extends javax.swing.JFrame {

    /**
     * Creates new form CreditosView
     */
    public CreditosView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCreditos = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        javax.swing.JLabel lblRedesSociais = new javax.swing.JLabel();
        btnVoltarMenuPrincipal = new javax.swing.JButton();
        lblRepositorio = new javax.swing.JLabel();
        jpTelaBordaCreditos = new javax.swing.JPanel();
        jpRepositoCor = new javax.swing.JPanel();
        jpRedesSociaisFundo = new javax.swing.JPanel();
        lblFundoCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtaCreditos.setEditable(false);
        jtaCreditos.setColumns(20);
        jtaCreditos.setRows(5);
        jtaCreditos.setText("================== SISTEMA CADFLEX ==================\n ====== SISTEMA ACADÊMICO DE CADASTRO FLEXÍVEL ======\n=================================================\n\nDesenvolvido em Java com Programação Orientada a Objetos (POO), \nintegrando conceitos modernos de estrutura de sistemas e interface gráfica.\n\nFuncionalidades Implementadas:\n→ Tela de Login  \n→ Tela de Registro  \n→ Tela Principal de Menu  \n→ Cadastro de Produtos (Incluir, Alterar, Excluir)  \n→ Visualização de Cadastros  \n→ Tela de Créditos  \n→ Splash Screen com Vídeo e Introdução Visual  \n→ Conexão com Banco de Dados (MySQL via JDBC)\n\nEstrutura Técnica:\n→ Arquitetura parcial baseada em MVC  \n→ Encapsulamento e Herança  \n→ Polimorfismo e Abstração  \n→ Uso de arquivos de mídia (imagens e vídeo)  \n→ Utilização de JFrames com interface Swing\n\nDesenvolvedor: Vitor Manoel Vidal Braz  \nSistema: CadFlex (Cadastro Flexível)  \nMotor Gráfica: VM ENGINE DEVELOPMENT - v1.5  \nUniversidade: UNIVALE - Universidade Vale do Rio Doce  \nCurso: Sistemas de Informação - 3º Período  \nDisciplina: Programação Orientada a Objetos (POO)  \n\nAgradecimento especial ao professor:  \nProf. Vitor Silva Ribeiro  \nPelo incentivo à criatividade e ao aprendizado.\n\n©vmengine2025 - Todos os direitos reservados");
        jtaCreditos.setWrapStyleWord(true);
        jtaCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jtaCreditos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 430, 580));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("Creditos do Sistema");
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 190, -1));

        lblRedesSociais.setBackground(new java.awt.Color(255, 255, 255));
        lblRedesSociais.setForeground(new java.awt.Color(255, 255, 255));
        lblRedesSociais.setText("<html><a href=''>Minhas Redes Sociais</a></html>");
        lblRedesSociais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        lblRedesSociais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRedesSociaisMouseClicked(evt);
            }
        });
        getContentPane().add(lblRedesSociais, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 630, 60, 60));

        btnVoltarMenuPrincipal.setText("← Voltar ao Menu Principal");
        btnVoltarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 700, 250, -1));

        lblRepositorio.setBackground(new java.awt.Color(255, 255, 255));
        lblRepositorio.setForeground(new java.awt.Color(0, 102, 204));
        lblRepositorio.setText("<html><a href=''>Repositorio do Projeto</a></html>");
        lblRepositorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        lblRepositorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRepositorioMouseClicked(evt);
            }
        });
        getContentPane().add(lblRepositorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, 80, 60));

        jpTelaBordaCreditos.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jpTelaBordaCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 630, 60, 60));

        jpRepositoCor.setBackground(new java.awt.Color(153, 153, 153));
        jpRepositoCor.setForeground(new java.awt.Color(255, 153, 51));
        getContentPane().add(jpRepositoCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, 80, 60));

        jpRedesSociaisFundo.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jpRedesSociaisFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 190, 40));

        lblFundoCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistema/imagens/TelaCreditos.png"))); // NOI18N
        lblFundoCreditos.setText("jLabel1");
        getContentPane().add(lblFundoCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2020, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuPrincipalActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVoltarMenuPrincipalActionPerformed

    private void lblRedesSociaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRedesSociaisMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://linktr.ee/vitormanoelvb"));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Não foi possível abrir o link.");
        }
    }//GEN-LAST:event_lblRedesSociaisMouseClicked

    private void lblRepositorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepositorioMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://github.com/vitormanoelvb/sistemacadastro-CadFlex/tree/main"));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Não foi possível abrir o repositório.");
        }
    }//GEN-LAST:event_lblRepositorioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpRedesSociaisFundo;
    private javax.swing.JPanel jpRepositoCor;
    private javax.swing.JPanel jpTelaBordaCreditos;
    private javax.swing.JTextArea jtaCreditos;
    private javax.swing.JLabel lblFundoCreditos;
    private javax.swing.JLabel lblRepositorio;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
