/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.view;
import com.mycompany.sistema.controller.ProdutoController;
import javax.swing.JFrame;

/**
 *
 * @author Vitor
 */
import javax.swing.JOptionPane;

public class ExcluirView extends javax.swing.JFrame {

    /**
     * Creates new form Excluir
     */
    public ExcluirView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExcluirProduto = new javax.swing.JLabel();
        lblIdProduto = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnVoltarAoMenuCadastro = new javax.swing.JButton();
        jpTelaExcluir = new javax.swing.JPanel();
        jpLadoExcluir = new javax.swing.JPanel();
        lblTelaExcluirProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExcluirProduto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblExcluirProduto.setForeground(new java.awt.Color(102, 102, 102));
        lblExcluirProduto.setText("EXCLUIR PRODUTO");
        lblExcluirProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(lblExcluirProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 200, 240, -1));

        lblIdProduto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblIdProduto.setText("ID do Produto:");
        getContentPane().add(lblIdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 90, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 142, -1));

        btnExcluir.setText("Excluir Produto");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 130, 40));

        btnVoltarAoMenuCadastro.setText("← Voltar ao Menu Cadastro");
        btnVoltarAoMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarAoMenuCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 760, 200, -1));

        jpTelaExcluir.setBackground(new java.awt.Color(0, 153, 255));
        jpTelaExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(jpTelaExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 270, 130));

        jpLadoExcluir.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jpLadoExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 230, 50));

        lblTelaExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistema/imagens/TelaExcluir.png"))); // NOI18N
        lblTelaExcluirProduto.setText("jLabel1");
        getContentPane().add(lblTelaExcluirProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2190, 1060));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            int id = Integer.parseInt(txtId.getText());

            ProdutoController controller = new ProdutoController();
            controller.excluirProduto(id);

            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            txtId.setText("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido! Digite um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarAoMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuCadastroActionPerformed
        TelaCadastroProdutoView telaCadastro = new TelaCadastroProdutoView();
        telaCadastro.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVoltarAoMenuCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltarAoMenuCadastro;
    private javax.swing.JPanel jpLadoExcluir;
    private javax.swing.JPanel jpTelaExcluir;
    private javax.swing.JLabel lblExcluirProduto;
    private javax.swing.JLabel lblIdProduto;
    private javax.swing.JLabel lblTelaExcluirProduto;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
