/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.view;
import com.mycompany.sistema.controller.ProdutoController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class IncluirView extends javax.swing.JFrame {

    /**
     * Creates new form Incluir
     */
    public IncluirView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovoProduto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblExtra = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        cbTipoProduto = new javax.swing.JComboBox<>();
        txtExtra = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnVoltarAoMenuCadastro = new javax.swing.JButton();
        jpTela = new javax.swing.JPanel();
        jpTelaCorida = new javax.swing.JPanel();
        lblFundoIncluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNovoProduto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblNovoProduto.setForeground(new java.awt.Color(102, 102, 102));
        lblNovoProduto.setText(" NOVO PRODUTO");
        lblNovoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(lblNovoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 220, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 220, 170, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 220, 40, 20));

        lblPreco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblPreco.setText("Preço:");
        getContentPane().add(lblPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 250, 40, 20));

        lblTipo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTipo.setText("Tipo:");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 280, 30, -1));

        lblExtra.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblExtra.setText("Info Extras:");
        getContentPane().add(lblExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 310, 70, 20));

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 250, 170, -1));

        cbTipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Físico", "Digital" }));
        cbTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(cbTipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 280, 70, -1));

        txtExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExtraActionPerformed(evt);
            }
        });
        getContentPane().add(txtExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 310, 170, -1));

        btnIncluir.setText("Incluir Produto");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 160, 40));

        btnVoltarAoMenuCadastro.setText("← Voltar ao Menu Cadastro");
        btnVoltarAoMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarAoMenuCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 760, 190, -1));

        jpTela.setBackground(new java.awt.Color(0, 153, 255));
        jpTela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(jpTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 320, 220));

        jpTelaCorida.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jpTelaCorida, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 220, 50));

        lblFundoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistema/imagens/incluir.png"))); // NOI18N
        lblFundoIncluir.setText("jLabel1");
        getContentPane().add(lblFundoIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoProdutoActionPerformed

    private void txtExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExtraActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        try {
            String nome = txtNome.getText().trim();
            String precoTexto = txtPreco.getText().trim().replace(",", ".");
            String tipo = cbTipoProduto.getSelectedItem().toString();
            String extra = txtExtra.getText().trim();

          if (nome.isEmpty() || precoTexto.isEmpty()) {
              throw new IllegalArgumentException("Nome e preço não podem estar vazios.");
            }

            double preco = Double.parseDouble(precoTexto);

            ProdutoController controller = new ProdutoController();
            controller.incluirProduto(nome, preco, tipo, extra);

            JOptionPane.showMessageDialog(this, "Produto incluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            txtNome.setText("");
            txtPreco.setText("");
            txtExtra.setText("");
            cbTipoProduto.setSelectedIndex(0);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Peso inválido. Digite um número com ponto, ex: 1.5 para 1,5 kg", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, "Erro ao incluir: " + iae.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro inesperado ao incluir: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnVoltarAoMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuCadastroActionPerformed
        TelaCadastroProdutoView telaCadastro = new TelaCadastroProdutoView();
        telaCadastro.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVoltarAoMenuCadastroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncluirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncluirView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnVoltarAoMenuCadastro;
    private javax.swing.JComboBox<String> cbTipoProduto;
    private javax.swing.JPanel jpTela;
    private javax.swing.JPanel jpTelaCorida;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblFundoIncluir;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNovoProduto;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtExtra;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
