/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.view;
import com.mycompany.sistema.controller.ProdutoController;
import com.mycompany.sistema.model.Produto;
import com.mycompany.sistema.model.ProdutoDigital;
import com.mycompany.sistema.model.ProdutoFisico;
import javax.swing.JFrame;

/**
 *
 * @author Vitor
 */
import javax.swing.JOptionPane;
public class AlterarView extends javax.swing.JFrame {
private ProdutoController controller = new ProdutoController();
    /**
     * Creates new form AlterarView
     */
    public AlterarView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlteraProduto = new javax.swing.JLabel();
        lblIDdoProduto = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cbTipoProduto = new javax.swing.JComboBox<>();
        lblExtra = new javax.swing.JLabel();
        txtExtra = new javax.swing.JTextField();
        btnSalvarAlteracoes = new javax.swing.JButton();
        btnVoltarAoMenuCadastro = new javax.swing.JButton();
        JpFundoPequeno = new javax.swing.JPanel();
        jpTelaFundoAlterar = new javax.swing.JPanel();
        lblTelaFundoAlterar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlteraProduto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblAlteraProduto.setForeground(new java.awt.Color(102, 102, 102));
        lblAlteraProduto.setText("ALTERAR PRODUTO");
        lblAlteraProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(lblAlteraProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 250, -1));

        lblIDdoProduto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblIDdoProduto.setText("ID do Produto:");
        getContentPane().add(lblIDdoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, 20));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 110, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 37, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 190, -1));

        lblPreco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblPreco.setText("Preço:");
        getContentPane().add(lblPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 190, -1));

        lblTipo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTipo.setText("Tipo:");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        cbTipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Físico", "Digital" }));
        cbTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(cbTipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        lblExtra.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblExtra.setText("Info Extra:");
        getContentPane().add(lblExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        txtExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExtraActionPerformed(evt);
            }
        });
        getContentPane().add(txtExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 190, -1));

        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarAlteracoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 150, 40));

        btnVoltarAoMenuCadastro.setText("← Voltar ao Menu Cadastro");
        btnVoltarAoMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarAoMenuCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 760, 200, -1));

        JpFundoPequeno.setBackground(new java.awt.Color(0, 153, 255));
        JpFundoPequeno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(JpFundoPequeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 310, 240));

        jpTelaFundoAlterar.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jpTelaFundoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 250, 50));

        lblTelaFundoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistema/imagens/alterar.png"))); // NOI18N
        lblTelaFundoAlterar.setText("jLabel1");
        getContentPane().add(lblTelaFundoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1850, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int id = Integer.parseInt(txtId.getText());
        Produto produto = controller.buscarProdutoPorId(id);

        if (produto != null) {
            txtNome.setText(produto.getNome());
            txtPreco.setText(String.valueOf(produto.getPreco()));
            cbTipoProduto.setSelectedItem(produto.getTipo());

            if (produto instanceof ProdutoFisico) {
                txtExtra.setText(String.valueOf(((ProdutoFisico) produto).getPeso()));
            } else if (produto instanceof ProdutoDigital) {
                txtExtra.setText(((ProdutoDigital) produto).getFormato());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado!");
        } 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void cbTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoProdutoActionPerformed

    private void txtExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExtraActionPerformed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        try {
        int id = Integer.parseInt(txtId.getText());
        String nome = txtNome.getText();
        double preco = Double.parseDouble(txtPreco.getText().replace(",", "."));
        String tipo = cbTipoProduto.getSelectedItem().toString();
        String extra = txtExtra.getText();

        ProdutoController controller = new ProdutoController();
        controller.alterarProduto(id, nome, preco, tipo, extra);

        JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!");

        // Limpa os campos
        txtId.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtExtra.setText("");
        cbTipoProduto.setSelectedIndex(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao alterar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void btnVoltarAoMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuCadastroActionPerformed
        TelaCadastroProdutoView telaCadastro = new TelaCadastroProdutoView();
        telaCadastro.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVoltarAoMenuCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpFundoPequeno;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JButton btnVoltarAoMenuCadastro;
    private javax.swing.JComboBox<String> cbTipoProduto;
    private javax.swing.JPanel jpTelaFundoAlterar;
    private javax.swing.JLabel lblAlteraProduto;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblIDdoProduto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTelaFundoAlterar;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtExtra;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
