/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.view;
import com.mycompany.sistema.SplashScreen;
import com.mycompany.sistema.DashBoardLogin;

/**
 *
 * @author Vitor
 */
public class TelaRecomendacoesView extends javax.swing.JFrame {

    /**
     * Creates new form TelaRecomendacoesView
     */
    public TelaRecomendacoesView() {
        setUndecorated(true);  
        initComponents();
        setSize(481, 291);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAviso = new javax.swing.JTextArea();
        btnIniciarSistema = new javax.swing.JButton();
        lblAtencao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtaAviso.setEditable(false);
        jtaAviso.setColumns(20);
        jtaAviso.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jtaAviso.setRows(5);
        jtaAviso.setText("Para melhor visualização do sistema, recomendo:\nUtilizar o sistema em tela cheia para funcionar adequadamente.\nIsso proporciona uma visualização otimizada dos menus, telas e \nfuncionalidades disponíveis. O sistema requer que o banco de dados \nesteja configurado corretamente para funcionar. As funções (incluir, \nalterar, excluir, etc.) e os menus dependem da conexão ativa com o banco.\nClique no botão abaixo para começar a usar o sistema.");
        jtaAviso.setWrapStyleWord(true);
        jtaAviso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jtaAviso);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 440, 150));

        btnIniciarSistema.setText("Inciar Sistema");
        btnIniciarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 120, 20));

        lblAtencao.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblAtencao.setForeground(new java.awt.Color(255, 0, 0));
        lblAtencao.setText("ATENÇÃO - ANTES DE CONTINUAR...");
        lblAtencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 9));
        jPanel1.add(lblAtencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 360, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSistemaActionPerformed
        dispose();
        SplashScreen splash = new SplashScreen(() -> {
            new DashBoardLogin().setVisible(true);
        });
    splash.mostrarSplash();
    }//GEN-LAST:event_btnIniciarSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRecomendacoesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSistema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaAviso;
    private javax.swing.JLabel lblAtencao;
    // End of variables declaration//GEN-END:variables
}
