/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.view;

import com.mycompany.sistema.MenuPrincipal;
import com.mycompany.sistema.model.Produto;
import com.mycompany.sistema.model.ProdutoFisico;
import com.mycompany.sistema.model.ProdutoDigital;
import com.mycompany.sistema.controller.ProdutoController;

/**
 *
 * @author Vitor
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JFrame;

public class VerCadastrosView extends javax.swing.JFrame {

    /**
     * Creates new form VerCadastrosView
     */
    public VerCadastrosView() {
        initComponents();
        carregarProdutosNaTabela();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnVoltarAoMenuPrincipal = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jpFundo1 = new javax.swing.JPanel();
        lblFundoVerCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Tipo", "Info Extra"
            }
        ));
        jScrollPane1.setViewportView(tblProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 110, 580, -1));

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, -1, -1));

        btnVoltarAoMenuPrincipal.setText("← Voltar ao Menu Principal");
        btnVoltarAoMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarAoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 760, 200, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("Lista de Produtos Cadastrados");
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 9));
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        jpFundo1.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jpFundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 350, 50));

        lblFundoVerCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistema/imagens/fundoVerCadastro.png"))); // NOI18N
        lblFundoVerCadastro.setText("jLabel1");
        getContentPane().add(lblFundoVerCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
      btnAtualizar.setEnabled(false);
      btnAtualizar.setText("Atualizando...");

      try {
          carregarProdutosNaTabela();
          JOptionPane.showMessageDialog(this, "Tabela atualizada com sucesso!");
          
      } catch (Exception e) {
          JOptionPane.showMessageDialog(this,
              "Erro ao atualizar tabela: " + e.getMessage(),
              "Erro",
              JOptionPane.ERROR_MESSAGE
            );
        } finally {
            btnAtualizar.setEnabled(true);
            btnAtualizar.setText("Atualizar");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnVoltarAoMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuPrincipalActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarAoMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    
   private void carregarProdutosNaTabela() {
    DefaultTableModel model = (DefaultTableModel) tblProdutos.getModel();
    model.setRowCount(0); 

    try {
        ProdutoController controller = new ProdutoController();
        List<Produto> produtos = controller.listarProdutos();

       for (Produto produto : produtos) {
    String extraInfo = "";

    if (produto instanceof ProdutoFisico) {
        extraInfo = ((ProdutoFisico) produto).getPeso() + " kg";
    } else if (produto instanceof ProdutoDigital) {
        extraInfo = ((ProdutoDigital) produto).getFormato();
    }

    Object[] rowData = {
        produto.getId(),
        produto.getNome(),
        produto.getPreco(),
        produto.getTipo(),
        extraInfo
    };
    model.addRow(rowData);
}
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Não foi possível carregar os produtos.\nErro: " + e.getMessage(), 
            "Erro de conexão", 
            JOptionPane.ERROR_MESSAGE);
    }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCadastrosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnVoltarAoMenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpFundo1;
    private javax.swing.JLabel lblFundoVerCadastro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProdutos;
    // End of variables declaration//GEN-END:variables
}
